<?php

namespace Database\Seeders;

use App\Models\Brand;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Category;
use App\Models\SubCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {

        // SubCategory::factory()->count(10)->create();
        // Category::factory()->count(10)->create();
        // Brand::factory()->count(10)->create();


        $subcategories = [
            ['name' => 'electronics', 'slug' => 'electronics'],
            ['name' => 'home-appliances', 'slug' => 'home-appliances'],
            ['name' => 'Sports', 'slug' => 'Sports'],
            ['name' => 'baby-products', 'slug' => 'baby-products'],
            ['name' => 'toys', 'slug' => 'toys'],
            ['name' => 'sports-equipment', 'slug' => 'sports-equipment'],
            ['name' => 'books', 'slug' => 'books'],
            ['name' => 'food-products', 'slug' => 'food-products'],
            ['name' => 'fitness-equipment', 'slug' => 'fitness-equipment'],
            ['name' => 'beverages', 'slug' => 'beverages'],
            ['name' => 'kitchen-supplies', 'slug' => 'kitchen-supplies'],
            ['name' => 'furniture', 'slug' => 'furniture'],
            ['name' => 'school-supplies', 'slug' => 'school-supplies'],
            ['name' => 'home-decor', 'slug' => 'home-decor'],
            ['name' => 'shoes', 'slug' => 'shoes'],
            ['name' => 'clothing', 'slug' => 'clothing'],
        ];
        DB::table('sub_categories')->insert($subcategories);




        $categories = [
            ['name' => 'mobiles', 'slug' => 'mobiles', 'sub_category_id' => 1],
            ['name' => 'computers', 'slug' => 'computers', 'sub_category_id' => 1],
            ['name' => 'Tv', 'slug' => 'Tv', 'sub_category_id' => 1],
            ['name' => 'wristwatches', 'slug' => 'wristwatches', 'sub_category_id' => 1],
            ['slug' => 'clothing&shoes',   'name' => 'clothing&shoes',   'sub_category_id' => 10],
            ['name' => 'refrigerators', 'slug' => 'refrigerators', 'sub_category_id' => 2],
            ['name' => 'washing-machines', 'slug' => 'washing-machines', 'sub_category_id' => 2],
            ['name' => 'microwaves', 'slug' => 'microwaves', 'sub_category_id' => 2],
            ['name' => 'air-conditioners', 'slug' => 'air-conditioners', 'sub_category_id' => 2],
            ['name' => 'football', 'slug' => 'football', 'sub_category_id' => 3],
            ['name' => 'basketball', 'slug' => 'basketball', 'sub_category_id' => 3],
            ['name' => 'tennis', 'slug' => 'tennis', 'sub_category_id' => 3],
            ['slug' => 'diapers',   'name' => 'diapers', 'sub_category_id' => 4],
            ['slug' => 'baby-food', 'name' => 'baby Food', 'sub_category_id' => 4,],
            ['slug' => 'baby-clothes', 'name' => 'baby Clothes', 'sub_category_id' => 4,],
            ['slug' => 'strollers', 'name' => 'strollers', 'sub_category_id' => 4,],
            ['slug' => 'educational-toys', 'name' => 'educational Toys', 'sub_category_id' => 5],
            ['slug' => 'soft-toys',        'name' => 'soft Toys',        'sub_category_id' => 5],
            ['slug' => 'action-figures',   'name' => 'action Figures',   'sub_category_id' => 5],
            ['slug' => 'puzzles',          'name' => 'puzzles',          'sub_category_id' => 5],
            ['slug' => 'treadmills',        'name' => 'treadmills',        'sub_category_id' => 6],
            ['slug' => 'dumbbells',         'name' => 'dumbbells',         'sub_category_id' => 6],
            ['slug' => 'exercise-bikes',    'name' => 'exercise Bikes',    'sub_category_id' => 6],
            ['slug' => 'yoga-mats',         'name' => 'yoga Mats',         'sub_category_id' => 6],
            ['slug' => 'fiction',        'name' => 'fiction',        'sub_category_id' => 7],
            ['slug' => 'non-fiction',    'name' => 'non-Fiction',    'sub_category_id' => 7],
            ['slug' => 'children-books', 'name' => 'children Books', 'sub_category_id' => 7],
            ['slug' => 'educational',    'name' => 'educational',    'sub_category_id' => 7],
            ['slug' => 'snacks',           'name' => 'snacks',           'sub_category_id' => 8],
            ['slug' => 'beverages',        'name' => 'beverages',        'sub_category_id' => 8],
            ['slug' => 'canned-food',      'name' => 'canned Food',      'sub_category_id' => 8],
            ['slug' => 'dry-goods',        'name' => 'dry Goods',        'sub_category_id' => 8],
            ['slug' => 'resistance-bands', 'name' => 'resistance Bands', 'sub_category_id' => 9],
            ['slug' => 'kettlebells',      'name' => 'kettlebells',      'sub_category_id' => 9],
            ['slug' => 'pull-up-bars',     'name' => 'pull-Up Bars',     'sub_category_id' => 9],
            ['slug' => 'foam-rollers',     'name' => 'foam Rollers',     'sub_category_id' => 9],
            ['slug' => 'mens-clothing',     'name' => 'men\'s Clothing',     'sub_category_id' => 10],
            ['slug' => 'women\'s-clothing',   'name' => 'women\'s Clothing',   'sub_category_id' => 10],
            ['slug' => 'kids-clothing',     'name' => 'kids Clothing',       'sub_category_id' => 10],
            ['slug' => 'accessories',       'name' => 'accessories',         'sub_category_id' => 10],
        ];
        DB::table('categories')->insert($categories);

        $brands = [
            ['name' => 'Samsung', 'slug' => 'samsung',   'sub_category_id' =>  1 ],
            ['name' => 'Apple', 'slug' => 'apple'    ,   'sub_category_id' =>  1 ],
            ['name' => 'Sony', 'slug' => 'sony'      ,   'sub_category_id' =>  1 ],
            ['name' => 'LG', 'slug' => 'lg'          ,   'sub_category_id' =>  1 ],
            ['name' => 'HP', 'slug' => 'hp'          ,   'sub_category_id' =>  1 ],
            ['name' => 'Dell', 'slug' => 'dell'      ,   'sub_category_id' =>  1     ],
            ['name' => 'Lenovo', 'slug' => 'lenovo'  ,   'sub_category_id' =>  1         ],
            ['name' => 'Asus', 'slug' => 'asus'      ,   'sub_category_id' =>  1     ],
            ['name' => 'Rolex', 'slug' => 'rolex'    ,   'sub_category_id' =>  1       ],
            ['name' => 'Casio', 'slug' => 'casio'    ,   'sub_category_id' =>  1       ],
            ['name' => 'Seiko', 'slug' => 'seiko'    ,   'sub_category_id' =>  1       ],
            ['name' => 'Garmin', 'slug' => 'garmin'  ,   'sub_category_id' =>  1         ],
            ['name' => 'Fossil', 'slug' => 'fossil'  ,   'sub_category_id' =>  1         ],
            ['name' => 'Nike', 'slug' => 'nike'      ,   'sub_category_id' =>  10     ],
            ['name' => 'Adidas', 'slug' => 'adidas'  ,   'sub_category_id' =>  10         ],
            ['name' => 'Puma', 'slug' => 'puma'      ,   'sub_category_id' =>  10     ],
            // ['name' => 'Nestle', 'slug' => 'nestle'],
            // ['name' => 'Pepsi', 'slug' => 'pepsi'],
            // ['name' => 'Coca-Cola', 'slug' => 'coca-cola'],
            // ['name' => 'Philips', 'slug' => 'philips'],
            // ['name' => 'Panasonic', 'slug' => 'panasonic'],
            // ['name' => 'Toshiba', 'slug' => 'toshiba'],
            // ['name' => 'Sharp', 'slug' => 'sharp'],
            // ['name' => 'Whirlpool', 'slug' => 'whirlpool'],
            // ['name' => 'Bosch', 'slug' => 'bosch'],
        ];
        DB::table('brands')->insert($brands);


        $faker = Faker::create();
        $products = [];

        for ($i = 1; $i <= 20; $i++) {
            $products[] = [
                'title' => $faker->unique()->name(),
                'slug' => $faker->unique()->slug(),
                'description' => $faker->text(200),
                'category_id' => rand(1, 9),
                'sub_category_id' => rand(1, 9),
                'brand_id' => rand(1, 16),
                'price' => $faker->randomFloat(2, 50, 500),
                'compare_price' => $faker->randomFloat(2, 60, 600),
                // 'is_featured' => $faker->randomElement(['yes', 'no']),
                'track_qty' => $faker->randomElement(['yes', 'no']),
                'sku' => 'SKU00' . $i,
                'qty' => $faker->numberBetween(1, 100),
                // 'showhome' => $faker->randomElement(['yes', 'no']),
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('products')->insert($products);








        // $products = [
        //     ['title' => 'Samsung Galaxy S24', 'slug' => 'samsung-galaxy-s24', 'description' => 'Latest Samsung smartphone', 'price' => 899.99, 'compare_price' => 999.99, 'category_id' => 1, 'sub_category_id' => 1, 'brand_id' => 1, 'image_id' => '1', 'sku' => 'SGS24-001', 'barcode' => '1000000000001', 'qty' => 50, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'iPhone 14 Pro', 'slug' => 'iphone-14-pro', 'description' => 'Newest Apple iPhone', 'price' => 1099.99, 'compare_price' => 1199.99, 'category_id' => 1,  'sub_category_id' => 1, 'brand_id' => 2, 'image_id' => '2', 'sku' => 'IP14PRO-002', 'barcode' => '1000000000002', 'qty' => 30, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'OnePlus 11', 'slug' => 'oneplus-11', 'description' => 'High-end Android phone', 'price' => 749.99, 'compare_price' => 849.99, 'category_id' => 1, 'sub_category_id' => 1, 'brand_id' => 3, 'image_id' => '3', 'sku' => 'OP11-003', 'barcode' => '1000000000003', 'qty' => 45, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Xiaomi Mi 13', 'slug' => 'xiaomi-mi-13', 'description' => 'Affordable flagship', 'price' => 599.99, 'compare_price' => 699.99, 'category_id' => 1, 'sub_category_id' => 1, 'brand_id' => 4, 'image_id' => '4', 'sku' => 'MI13-004', 'barcode' => '1000000000004', 'qty' => 60, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Nokia X200', 'slug' => 'nokia-x200', 'description' => 'Reliable mobile phone', 'price' => 199.99, 'compare_price' => 249.99, 'category_id' => 1, 'sub_category_id' => 1, 'brand_id' => 5, 'image_id' => '5', 'sku' => 'NX200-005', 'barcode' => '1000000000005', 'qty' => 70, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Google Pixel 8', 'slug' => 'google-pixel-8', 'description' => 'Google flagship phone', 'price' => 899.99, 'compare_price' => 999.99, 'category_id' => 1, 'sub_category_id' => 1, 'brand_id' => 6, 'image_id' => '6', 'sku' => 'GP8-006', 'barcode' => '1000000000006', 'qty' => 40, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],

        //     ['title' => 'Dell Inspiron 15', 'slug' => 'dell-inspiron-15', 'description' => 'Affordable laptop from Dell', 'price' => 699.99, 'compare_price' => 799.99, 'category_id' => 2, 'sub_category_id' => 1, 'brand_id' => 7, 'image_id' => '7', 'sku' => 'DI15-007', 'barcode' => '1000000000007', 'qty' => 30, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Apple MacBook Air M2', 'slug' => 'macbook-air-m2', 'description' => 'Lightweight Apple laptop', 'price' => 1299.99, 'compare_price' => 1499.99, 'category_id' => 2, 'sub_category_id' => 1, 'brand_id' => 2, 'image_id' => '8', 'sku' => 'MBA2-008', 'barcode' => '1000000000008', 'qty' => 20, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'HP Pavilion', 'slug' => 'hp-pavilion', 'description' => 'Popular HP model', 'price' => 599.99, 'compare_price' => 699.99, 'category_id' => 2, 'sub_category_id' => 1, 'brand_id' => 8, 'image_id' => '9', 'sku' => 'HPPAV-009', 'barcode' => '1000000000009', 'qty' => 35, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Lenovo ThinkPad E15', 'slug' => 'lenovo-thinkpad-e15', 'description' => 'Business class laptop', 'price' => 899.99, 'compare_price' => 999.99, 'category_id' => 2, 'sub_category_id' => 1, 'brand_id' => 9, 'image_id' => '10', 'sku' => 'LTE15-010', 'barcode' => '1000000000010', 'qty' => 25, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Asus ZenBook', 'slug' => 'asus-zenbook', 'description' => 'Compact and powerful', 'price' => 999.99, 'compare_price' => 1099.99, 'category_id' => 2, 'sub_category_id' => 1, 'brand_id' => 10, 'image_id' => '11', 'sku' => 'AZB-011', 'barcode' => '1000000000011', 'qty' => 28, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'MSI Gaming Laptop', 'slug' => 'msi-gaming-laptop', 'description' => 'Gaming powerhouse', 'price' => 1399.99, 'compare_price' => 1599.99, 'category_id' => 2, 'sub_category_id' => 1, 'brand_id' => 11, 'image_id' => '12', 'sku' => 'MSIG-012', 'barcode' => '1000000000012', 'qty' => 15, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],

        //     ['title' => 'Samsung 55" Smart TV', 'slug' => 'samsung-55-smart-tv', 'description' => '4K UHD Smart TV', 'price' => 599.99, 'compare_price' => 659.99, 'category_id' => 3, 'sub_category_id' => 1, 'brand_id' => 12, 'image_id' => '13', 'sku' => 'TV-013', 'barcode' => '1000000000013', 'qty' => 28, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'LG OLED CX', 'slug' => 'lg-oled-cx', 'description' => 'High-end OLED TV', 'price' => 1299.99, 'compare_price' => 1429.99, 'category_id' => 3, 'sub_category_id' => 1, 'brand_id' => 13, 'image_id' => '14', 'sku' => 'TV-014', 'barcode' => '1000000000014', 'qty' => 39, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Sony Bravia X90J', 'slug' => 'sony-bravia-x90j', 'description' => 'Full Array LED TV', 'price' => 999.99, 'compare_price' => 1099.99, 'category_id' => 3, 'sub_category_id' => 1, 'brand_id' => 14, 'image_id' => '15', 'sku' => 'TV-015', 'barcode' => '1000000000015', 'qty' => 27, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'TCL Roku TV 50"', 'slug' => 'tcl-roku-tv-50', 'description' => 'Budget 4K Smart TV', 'price' => 349.99, 'compare_price' => 384.99, 'category_id' => 3, 'sub_category_id' => 1, 'brand_id' => 15, 'image_id' => '16', 'sku' => 'TV-016', 'barcode' => '1000000000016', 'qty' => 61, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Hisense U8G', 'slug' => 'hisense-u8g', 'description' => 'Premium ULED TV', 'price' => 749.99, 'compare_price' => 824.99, 'category_id' => 3, 'sub_category_id' => 1, 'brand_id' => 16, 'image_id' => '17', 'sku' => 'TV-017', 'barcode' => '1000000000017', 'qty' => 40, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Panasonic HX700', 'slug' => 'panasonic-hx700', 'description' => 'Smart LED TV', 'price' => 499.99, 'compare_price' => 549.99, 'category_id' => 3, 'sub_category_id' => 1, 'brand_id' => 17, 'image_id' => '18', 'sku' => 'TV-018', 'barcode' => '1000000000018', 'qty' => 60, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],


        //     ['title' => 'Rolex Submariner', 'slug' => 'rolex-submariner', 'description' => 'Luxury diving watch by Rolex', 'price' => 7999.99, 'compare_price' => 8999.99, 'category_id' => 4, 'sub_category_id' => 1, 'brand_id' => 4, 'image_id' => '4', 'sku' => 'RW-001', 'barcode' => '1000000000025', 'qty' => 10, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Casio G-Shock GA-2100', 'slug' => 'casio-g-shock-ga-2100', 'description' => 'Durable and stylish G-Shock watch', 'price' => 99.99, 'compare_price' => 129.99, 'category_id' => 4, 'sub_category_id' => 1, 'brand_id' => 4, 'image_id' => '4', 'sku' => 'RW-002', 'barcode' => '1000000000026', 'qty' => 100, 'status' => 1, 'is_featured' => 'no', 'track_qty' => 'yes', 'showhome' => 'no'],
        //     ['title' => 'Apple Watch Series 9', 'slug' => 'apple-watch-series-9', 'description' => 'Smartwatch with health tracking features', 'price' => 399.99, 'compare_price' => 449.99, 'category_id' => 4, 'sub_category_id' => 1, 'brand_id' => 4, 'image_id' => '4', 'sku' => 'RW-003', 'barcode' => '1000000000027', 'qty' => 35, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Fossil Gen 6', 'slug' => 'fossil-gen-6', 'description' => 'Hybrid smartwatch from Fossil', 'price' => 219.99, 'compare_price' => 249.99, 'category_id' => 4, 'sub_category_id' => 1, 'brand_id' => 4, 'image_id' => '4', 'sku' => 'RW-004', 'barcode' => '1000000000028', 'qty' => 60, 'status' => 1, 'is_featured' => 'no', 'track_qty' => 'yes', 'showhome' => 'no'],
        //     ['title' => 'Seiko 5 Sports', 'slug' => 'seiko-5-sports', 'description' => 'Automatic watch by Seiko', 'price' => 149.99, 'compare_price' => 179.99, 'category_id' => 4, 'sub_category_id' => 1, 'brand_id' => 4, 'image_id' => '4', 'sku' => 'RW-005', 'barcode' => '1000000000029', 'qty' => 40, 'status' => 1, 'is_featured' => 'no', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Garmin Forerunner 255', 'slug' => 'garmin-forerunner-255', 'description' => 'GPS running smartwatch by Garmin', 'price' => 299.99, 'compare_price' => 349.99, 'category_id' => 4, 'sub_category_id' => 1, 'brand_id' => 4, 'image_id' => '4', 'sku' => 'RW-006', 'barcode' => '1000000000030', 'qty' => 25, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],


        //     ['title' => 'LG Front Load Washer', 'slug' => 'lg-front-load-washer', 'description' => 'Efficient front load washing machine by LG', 'price' => 649.99, 'compare_price' => 699.99, 'category_id' => 6, 'sub_category_id' => 2, 'brand_id' => 2, 'image_id' => '16', 'sku' => 'LGWM-001', 'barcode' => '1000000000021', 'qty' => 30, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Samsung EcoBubble', 'slug' => 'samsung-ecobubble', 'description' => 'Samsung EcoBubble smart washer', 'price' => 599.99, 'compare_price' => 649.99, 'category_id' => 6, 'sub_category_id' => 2, 'brand_id' => 1, 'image_id' => '17', 'sku' => 'SEB-001', 'barcode' => '1000000000022', 'qty' => 40, 'status' => 1, 'is_featured' => 'no', 'track_qty' => 'yes', 'showhome' => 'no'],
        //     ['title' => 'Bosch Series 6', 'slug' => 'bosch-series-6', 'description' => 'Reliable and silent washer from Bosch', 'price' => 719.99, 'compare_price' => 769.99, 'category_id' => 6, 'sub_category_id' => 2, 'brand_id' => 3, 'image_id' => '18', 'sku' => 'BS6-001', 'barcode' => '1000000000023', 'qty' => 25, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Whirlpool Supreme Care', 'slug' => 'whirlpool-supreme-care', 'description' => 'Top performance washing machine from Whirlpool', 'price' => 689.99, 'compare_price' => 749.99, 'category_id' => 6, 'sub_category_id' => 2, 'brand_id' => 4, 'image_id' => '19', 'sku' => 'WSC-001', 'barcode' => '1000000000024', 'qty' => 35, 'status' => 1, 'is_featured' => 'no', 'track_qty' => 'yes', 'showhome' => 'no'],
        //     ['title' => 'Electrolux UltraCare', 'slug' => 'electrolux-ultracare', 'description' => 'Premium care for clothes', 'price' => 799.99, 'compare_price' => 849.99, 'category_id' => 6, 'sub_category_id' => 2, 'brand_id' => 5, 'image_id' => '20', 'sku' => 'EUC-001', 'barcode' => '1000000000025', 'qty' => 20, 'status' => 1, 'is_featured' => 'yes', 'track_qty' => 'yes', 'showhome' => 'yes'],
        //     ['title' => 'Panasonic Smart Inverter', 'slug' => 'panasonic-smart-inverter', 'description' => 'Smart inverter motor washer from Panasonic', 'price' => 629.99, 'compare_price' => 679.99, 'category_id' => 6, 'sub_category_id' => 2, 'brand_id' => 6, 'image_id' => '21', 'sku' => 'PSI-001', 'barcode' => '1000000000026', 'qty' => 28, 'status' => 1, 'is_featured' => 'no', 'track_qty' => 'yes', 'showhome' => 'no'],



        // ];







        $countries = array(
            array('code' => 'US', 'name' => 'United States'),
            array('code' => 'CA', 'name' => 'Canada'),
            array('code' => 'AF', 'name' => 'Afghanistan'),
            array('code' => 'AL', 'name' => 'Albania'),
            array('code' => 'DZ', 'name' => 'Algeria'),
            array('code' => 'AS', 'name' => 'American Samoa'),
            array('code' => 'AD', 'name' => 'Andorra'),
            array('code' => 'AO', 'name' => 'Angola'),
            array('code' => 'AI', 'name' => 'Anguilla'),
            array('code' => 'AQ', 'name' => 'Antarctica'),
            array('code' => 'AG', 'name' => 'Antigua and/or Barbuda'),
            array('code' => 'AR', 'name' => 'Argentina'),
            array('code' => 'AM', 'name' => 'Armenia'),
            array('code' => 'AW', 'name' => 'Aruba'),
            array('code' => 'AU', 'name' => 'Australia'),
            array('code' => 'AT', 'name' => 'Austria'),
            array('code' => 'AZ', 'name' => 'Azerbaijan'),
            array('code' => 'BS', 'name' => 'Bahamas'),
            array('code' => 'BH', 'name' => 'Bahrain'),
            array('code' => 'BD', 'name' => 'Bangladesh'),
            array('code' => 'BB', 'name' => 'Barbados'),
            array('code' => 'BY', 'name' => 'Belarus'),
            array('code' => 'BE', 'name' => 'Belgium'),
            array('code' => 'BZ', 'name' => 'Belize'),
            array('code' => 'BJ', 'name' => 'Benin'),
            array('code' => 'BM', 'name' => 'Bermuda'),
            array('code' => 'BT', 'name' => 'Bhutan'),
            array('code' => 'BO', 'name' => 'Bolivia'),
            array('code' => 'BA', 'name' => 'Bosnia and Herzegovina'),
            array('code' => 'BW', 'name' => 'Botswana'),
            array('code' => 'BV', 'name' => 'Bouvet Island'),
            array('code' => 'BR', 'name' => 'Brazil'),
            array('code' => 'IO', 'name' => 'British lndian Ocean Territory'),
            array('code' => 'BN', 'name' => 'Brunei Darussalam'),
            array('code' => 'BG', 'name' => 'Bulgaria'),
            array('code' => 'BF', 'name' => 'Burkina Faso'),
            array('code' => 'BI', 'name' => 'Burundi'),
            array('code' => 'KH', 'name' => 'Cambodia'),
            array('code' => 'CM', 'name' => 'Cameroon'),
            array('code' => 'CV', 'name' => 'Cape Verde'),
            array('code' => 'KY', 'name' => 'Cayman Islands'),
            array('code' => 'CF', 'name' => 'Central African Republic'),
            array('code' => 'TD', 'name' => 'Chad'),
            array('code' => 'CL', 'name' => 'Chile'),
            array('code' => 'CN', 'name' => 'China'),
            array('code' => 'CX', 'name' => 'Christmas Island'),
            array('code' => 'CC', 'name' => 'Cocos (Keeling) Islands'),
            array('code' => 'CO', 'name' => 'Colombia'),
            array('code' => 'KM', 'name' => 'Comoros'),
            array('code' => 'CG', 'name' => 'Congo'),
            array('code' => 'CK', 'name' => 'Cook Islands'),
            array('code' => 'CR', 'name' => 'Costa Rica'),
            array('code' => 'HR', 'name' => 'Croatia (Hrvatska)'),
            array('code' => 'CU', 'name' => 'Cuba'),
            array('code' => 'CY', 'name' => 'Cyprus'),
            array('code' => 'CZ', 'name' => 'Czech Republic'),
            array('code' => 'CD', 'name' => 'Democratic Republic of Congo'),
            array('code' => 'DK', 'name' => 'Denmark'),
            array('code' => 'DJ', 'name' => 'Djibouti'),
            array('code' => 'DM', 'name' => 'Dominica'),
            array('code' => 'DO', 'name' => 'Dominican Republic'),
            array('code' => 'TP', 'name' => 'East Timor'),
            array('code' => 'EC', 'name' => 'Ecudaor'),
            array('code' => 'EG', 'name' => 'Egypt'),
            array('code' => 'SV', 'name' => 'El Salvador'),
            array('code' => 'GQ', 'name' => 'Equatorial Guinea'),
            array('code' => 'ER', 'name' => 'Eritrea'),
            array('code' => 'EE', 'name' => 'Estonia'),
            array('code' => 'ET', 'name' => 'Ethiopia'),
            array('code' => 'FK', 'name' => 'Falkland Islands (Malvinas)'),
            array('code' => 'FO', 'name' => 'Faroe Islands'),
            array('code' => 'FJ', 'name' => 'Fiji'),
            array('code' => 'FI', 'name' => 'Finland'),
            array('code' => 'FR', 'name' => 'France'),
            array('code' => 'FX', 'name' => 'France, Metropolitan'),
            array('code' => 'GF', 'name' => 'French Guiana'),
            array('code' => 'PF', 'name' => 'French Polynesia'),
            array('code' => 'TF', 'name' => 'French Southern Territories'),
            array('code' => 'GA', 'name' => 'Gabon'),
            array('code' => 'GM', 'name' => 'Gambia'),
            array('code' => 'GE', 'name' => 'Georgia'),
            array('code' => 'DE', 'name' => 'Germany'),
            array('code' => 'GH', 'name' => 'Ghana'),
            array('code' => 'GI', 'name' => 'Gibraltar'),
            array('code' => 'GR', 'name' => 'Greece'),
            array('code' => 'GL', 'name' => 'Greenland'),
            array('code' => 'GD', 'name' => 'Grenada'),
            array('code' => 'GP', 'name' => 'Guadeloupe'),
            array('code' => 'GU', 'name' => 'Guam'),
            array('code' => 'GT', 'name' => 'Guatemala'),
            array('code' => 'GN', 'name' => 'Guinea'),
            array('code' => 'GW', 'name' => 'Guinea-Bissau'),
            array('code' => 'GY', 'name' => 'Guyana'),
            array('code' => 'HT', 'name' => 'Haiti'),
            array('code' => 'HM', 'name' => 'Heard and Mc Donald Islands'),
            array('code' => 'HN', 'name' => 'Honduras'),
            array('code' => 'HK', 'name' => 'Hong Kong'),
            array('code' => 'HU', 'name' => 'Hungary'),
            array('code' => 'IS', 'name' => 'Iceland'),
            array('code' => 'IN', 'name' => 'India'),
            array('code' => 'ID', 'name' => 'Indonesia'),
            array('code' => 'IR', 'name' => 'Iran (Islamic Republic of)'),
            array('code' => 'IQ', 'name' => 'Iraq'),
            array('code' => 'IE', 'name' => 'Ireland'),
            array('code' => 'IL', 'name' => 'Israel'),
            array('code' => 'IT', 'name' => 'Italy'),
            array('code' => 'CI', 'name' => 'Ivory Coast'),
            array('code' => 'JM', 'name' => 'Jamaica'),
            array('code' => 'JP', 'name' => 'Japan'),
            array('code' => 'JO', 'name' => 'Jordan'),
            array('code' => 'KZ', 'name' => 'Kazakhstan'),
            array('code' => 'KE', 'name' => 'Kenya'),
            array('code' => 'KI', 'name' => 'Kiribati'),
            array('code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of'),
            array('code' => 'KR', 'name' => 'Korea, Republic of'),
            array('code' => 'KW', 'name' => 'Kuwait'),
            array('code' => 'KG', 'name' => 'Kyrgyzstan'),
            array('code' => 'LA', 'name' => 'Lao People\'s Democratic Republic'),
            array('code' => 'LV', 'name' => 'Latvia'),
            array('code' => 'LB', 'name' => 'Lebanon'),
            array('code' => 'LS', 'name' => 'Lesotho'),
            array('code' => 'LR', 'name' => 'Liberia'),
            array('code' => 'LY', 'name' => 'Libyan Arab Jamahiriya'),
            array('code' => 'LI', 'name' => 'Liechtenstein'),
            array('code' => 'LT', 'name' => 'Lithuania'),
            array('code' => 'LU', 'name' => 'Luxembourg'),
            array('code' => 'MO', 'name' => 'Macau'),
            array('code' => 'MK', 'name' => 'Macedonia'),
            array('code' => 'MG', 'name' => 'Madagascar'),
            array('code' => 'MW', 'name' => 'Malawi'),
            array('code' => 'MY', 'name' => 'Malaysia'),
            array('code' => 'MV', 'name' => 'Maldives'),
            array('code' => 'ML', 'name' => 'Mali'),
            array('code' => 'MT', 'name' => 'Malta'),
            array('code' => 'MH', 'name' => 'Marshall Islands'),
            array('code' => 'MQ', 'name' => 'Martinique'),
            array('code' => 'MR', 'name' => 'Mauritania'),
            array('code' => 'MU', 'name' => 'Mauritius'),
            array('code' => 'TY', 'name' => 'Mayotte'),
            array('code' => 'MX', 'name' => 'Mexico'),
            array('code' => 'FM', 'name' => 'Micronesia, Federated States of'),
            array('code' => 'MD', 'name' => 'Moldova, Republic of'),
            array('code' => 'MC', 'name' => 'Monaco'),
            array('code' => 'MN', 'name' => 'Mongolia'),
            array('code' => 'MS', 'name' => 'Montserrat'),
            array('code' => 'MA', 'name' => 'Morocco'),
            array('code' => 'MZ', 'name' => 'Mozambique'),
            array('code' => 'MM', 'name' => 'Myanmar'),
            array('code' => 'NA', 'name' => 'Namibia'),
            array('code' => 'NR', 'name' => 'Nauru'),
            array('code' => 'NP', 'name' => 'Nepal'),
            array('code' => 'NL', 'name' => 'Netherlands'),
            array('code' => 'AN', 'name' => 'Netherlands Antilles'),
            array('code' => 'NC', 'name' => 'New Caledonia'),
            array('code' => 'NZ', 'name' => 'New Zealand'),
            array('code' => 'NI', 'name' => 'Nicaragua'),
            array('code' => 'NE', 'name' => 'Niger'),
            array('code' => 'NG', 'name' => 'Nigeria'),
            array('code' => 'NU', 'name' => 'Niue'),
            array('code' => 'NF', 'name' => 'Norfork Island'),
            array('code' => 'MP', 'name' => 'Northern Mariana Islands'),
            array('code' => 'NO', 'name' => 'Norway'),
            array('code' => 'OM', 'name' => 'Oman'),
            array('code' => 'PK', 'name' => 'Pakistan'),
            array('code' => 'PW', 'name' => 'Palau'),
            array('code' => 'PA', 'name' => 'Panama'),
            array('code' => 'PG', 'name' => 'Papua New Guinea'),
            array('code' => 'PY', 'name' => 'Paraguay'),
            array('code' => 'PE', 'name' => 'Peru'),
            array('code' => 'PH', 'name' => 'Philippines'),
            array('code' => 'PN', 'name' => 'Pitcairn'),
            array('code' => 'PL', 'name' => 'Poland'),
            array('code' => 'PT', 'name' => 'Portugal'),
            array('code' => 'PR', 'name' => 'Puerto Rico'),
            array('code' => 'QA', 'name' => 'Qatar'),
            array('code' => 'SS', 'name' => 'Republic of South Sudan'),
            array('code' => 'RE', 'name' => 'Reunion'),
            array('code' => 'RO', 'name' => 'Romania'),
            array('code' => 'RU', 'name' => 'Russian Federation'),
            array('code' => 'RW', 'name' => 'Rwanda'),
            array('code' => 'KN', 'name' => 'Saint Kitts and Nevis'),
            array('code' => 'LC', 'name' => 'Saint Lucia'),
            array('code' => 'VC', 'name' => 'Saint Vincent and the Grenadines'),
            array('code' => 'WS', 'name' => 'Samoa'),
            array('code' => 'SM', 'name' => 'San Marino'),
            array('code' => 'ST', 'name' => 'Sao Tome and Principe'),
            array('code' => 'SA', 'name' => 'Saudi Arabia'),
            array('code' => 'SN', 'name' => 'Senegal'),
            array('code' => 'RS', 'name' => 'Serbia'),
            array('code' => 'SC', 'name' => 'Seychelles'),
            array('code' => 'SL', 'name' => 'Sierra Leone'),
            array('code' => 'SG', 'name' => 'Singapore'),
            array('code' => 'SK', 'name' => 'Slovakia'),
            array('code' => 'SI', 'name' => 'Slovenia'),
            array('code' => 'SB', 'name' => 'Solomon Islands'),
            array('code' => 'SO', 'name' => 'Somalia'),
            array('code' => 'ZA', 'name' => 'South Africa'),
            array('code' => 'GS', 'name' => 'South Georgia South Sandwich Islands'),
            array('code' => 'ES', 'name' => 'Spain'),
            array('code' => 'LK', 'name' => 'Sri Lanka'),
            array('code' => 'SH', 'name' => 'St. Helena'),
            array('code' => 'PM', 'name' => 'St. Pierre and Miquelon'),
            array('code' => 'SD', 'name' => 'Sudan'),
            array('code' => 'SR', 'name' => 'Suriname'),
            array('code' => 'SJ', 'name' => 'Svalbarn and Jan Mayen Islands'),
            array('code' => 'SZ', 'name' => 'Swaziland'),
            array('code' => 'SE', 'name' => 'Sweden'),
            array('code' => 'CH', 'name' => 'Switzerland'),
            array('code' => 'SY', 'name' => 'Syrian Arab Republic'),
            array('code' => 'TW', 'name' => 'Taiwan'),
            array('code' => 'TJ', 'name' => 'Tajikistan'),
            array('code' => 'TZ', 'name' => 'Tanzania, United Republic of'),
            array('code' => 'TH', 'name' => 'Thailand'),
            array('code' => 'TG', 'name' => 'Togo'),
            array('code' => 'TK', 'name' => 'Tokelau'),
            array('code' => 'TO', 'name' => 'Tonga'),
            array('code' => 'TT', 'name' => 'Trinidad and Tobago'),
            array('code' => 'TN', 'name' => 'Tunisia'),
            array('code' => 'TR', 'name' => 'Turkey'),
            array('code' => 'TM', 'name' => 'Turkmenistan'),
            array('code' => 'TC', 'name' => 'Turks and Caicos Islands'),
            array('code' => 'TV', 'name' => 'Tuvalu'),
            array('code' => 'UG', 'name' => 'Uganda'),
            array('code' => 'UA', 'name' => 'Ukraine'),
            array('code' => 'AE', 'name' => 'United Arab Emirates'),
            array('code' => 'GB', 'name' => 'United Kingdom'),
            array('code' => 'UM', 'name' => 'United States minor outlying islands'),
            array('code' => 'UY', 'name' => 'Uruguay'),
            array('code' => 'UZ', 'name' => 'Uzbekistan'),
            array('code' => 'VU', 'name' => 'Vanuatu'),
            array('code' => 'VA', 'name' => 'Vatican City State'),
            array('code' => 'VE', 'name' => 'Venezuela'),
            array('code' => 'VN', 'name' => 'Vietnam'),
            array('code' => 'VG', 'name' => 'Virgin Islands (British)'),
            array('code' => 'VI', 'name' => 'Virgin Islands (U.S.)'),
            array('code' => 'WF', 'name' => 'Wallis and Futuna Islands'),
            array('code' => 'EH', 'name' => 'Western Sahara'),
            array('code' => 'YE', 'name' => 'Yemen'),
            array('code' => 'YU', 'name' => 'Yugoslavia'),
            array('code' => 'ZR', 'name' => 'Zaire'),
            array('code' => 'ZM', 'name' => 'Zambia'),
            array('code' => 'ZW', 'name' => 'Zimbabwe'),
        );

        DB::table('countries')->insert($countries);

        $users  = [
            'name' => "user",
            'email' => "user@example.com",
            'password' => Hash::make("user"),
            'phone' => "01068869740",
        ];
        DB::table('users')->insert($users);

        $admins  = [
            'name' => "admin",
            'email' => "admin@example.com",
            'password' => Hash::make("admin"),
        ];
        DB::table('admins')->insert($admins);
    }
}
